# Copyright (c) 2013-2018 Sebastien Rombauts (sebastien.rombauts@gmail.com)

language: cpp

# compilers to add to build matrix
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake ..

# build app, and run tests (ie make & make test)
script:
  - cmake --build .
  - ctest --output-on-failure

