# Copyright (c) 2013-2018 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

# scripts that run after cloning repository
# NOTE : not updating submodule as cloning googletest does not work on AppVeyor
install:
  - git submodule update --init cpplint
# - git submodule update --init googletest

# configurations to add to build matrix
configuration:
  - Debug
  - Release
 
# scripts to run before build
# NOTE : no unit tests as cloning googletest does not work on AppVeyor
before_build:
  - mkdir build
  - cd build
  - cmake -DCPPSKELETON_RUN_TESTS=OFF ..

# build app
build_script:
  - cmake --build .
# - ctest --output-on-failure
